import Head from "next/head";
import { Inter } from "next/font/google";
import Slider from "@/components/Slider";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Slider Setup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-center pt-10">
        <h1 className="text-secondary text-3xl font-semibold">
          <span className="text-main text-2xl font-bold mr-3">/</span>Reviews
        </h1>
          <Slider />
      </main>
    </>
  );
}
